version: "2"
services:
  cli:
    build: .
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - ${PORT}:${PORT}
    command: ng serve --host=0.0.0.0 --port ${PORT}
